name: SyncCommands
version: '${project.version}'
main: me.itswagpvp.synccommands.spigot.SyncCommands
api-version: 1.13
authors: [ _ItsWagPvP ]
description: Sync commands over servers (Spigot/Bungee) with MySQL
website: https://dev.itswagpvp.eu
commands:
  sync:
    aliases:
      - commandsync
    usage: /<command>
  synccommands:
    aliases:
      - sc
    usage: /<command>